JMC.Portal.Web.UI/Controllers/MenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JMC.Portal.Web.UI.Helpers;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;

namespace JMC.Portal.Web.UI.Controllers
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly MenuHelper _cbaMenuHelper = new MenuHelper();

        public async Task<IViewComponentResult> InvokeAsync(int testId)
        {
            //testId is optional, and can be passed in when you call InvokeAsync
            //Parse current URL to determine which menu item to highlight:
            string baseUrl = Request.Scheme + "://" + Request.Host.Value;
            var httpRequestFeature = Request.HttpContext.Features.Get<IHttpRequestFeature>();
            var uri = httpRequestFeature.RawTarget; /*+ Request.RouteValues["controller"] + httpRequestFeature.RawTarget + Request.RouteValues["action"];*/
            var id = HttpContext.Request.Query["id"].ToString();  //Parse Query String
            var menuItems = await _cbaMenuHelper.GetAllMenuItems(baseUrl + uri, id); //Can pass in testId here if required.
            return View("_MenuPartial", menuItems);
        }
    }
}

JMC.Portal.Web.UI/Controllers/SideMenuViewComponent.cs
using JMC.Portal.Web.UI.Helpers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JMC.Portal.Web.UI.Controllers
{
    public class SideMenuViewComponent : ViewComponent
    {
        private readonly MenuHelper _sideMenuHelper = new MenuHelper();

        public async Task<IViewComponentResult> InvokeAsync(string mainMenu)
        {           
            var menuItems = await _sideMenuHelper.GetSideMenuItems(mainMenu); //Can pass in testId here if required.
            return View("_SideMenuPartial", _sideMenuHelper.GetMenu(menuItems, null));
        }
    }
}

JMC.Portal.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <style>

        .selected {
            background-color: #941800;
            color: white;
        }

        .selected a {
            color: white !important;
        }

        nav a:hover {
            background-color: #555 !important;
            border: 1px solid black;
        }

        nav a.active {
            background-color: #555 !important;
        }

        .sidenav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            width: 200px;
          /*  background-color: #941800;*/
            background-color: #f1f1f1;
            position: fixed;
            height: 100%;
            overflow: auto;
            transition: 0.5s;
            padding-top: 10px;
            margin-top: 30px;
        }


            .sidenav a {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 15px;
                color: #4E4E4E;
                background-color: transparent;
                display: block;
                border: none;
                /*background: none;*/
                width: 100%;
                text-align: left;
                cursor: pointer;
                outline: none;
            }

            .dropdown-btn {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 15px;
                color: #4E4E4E;
                background-color: transparent;
                display: block;
                border: none;
                /*background: none;*/
                width: 195px;
                text-align: left;
                cursor: pointer;
                outline: none;
                margin: 1px;
            }

                /* On mouse-over */
                .sidenav a:hover, .dropdown-btn:hover {
                    color: #4E4E4E;
                    background-color: transparent;
                    font-size: 15px;
                }

        .dropdown-container > li:hover {
            color: white !important;
            text-decoration: none;
            background-color: #941800;
        }

        .dropdown-container > li > a:hover {
            color: white !important;
            text-decoration: none;
            margin:1px;
        }

        .dropdown-container > li > a:active {
            color: white !important;
            text-decoration: none;
        }

         /*Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
        .dropdown-container {
            display: block;
            background-image: url("/images/darkTheme/backgroundLeftNavWideSubMenu.png");
            background-repeat: repeat;
            padding-left: 1px;
        }


         /*Optional: Style the caret down icon */
        .fa-caret-down {
            float: right;
            padding-right: 8px;
        }


        .dropdown {
            text-decoration: none;
            font-size: 15px;
            color: #4E4E4E;
            background-color: transparent;
            display: block;
            border: none;
        background: none;
        width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }

        .navbar-dark {
            color: #FFFFFF;
            background-color: #941800;
        }

        .white-text {
            color: white !important;
        }

        body {
            font-family: "Lato", sans-serif;
        }

        .wrapper {
            width: 100%;
        }

        #main {
            transition: margin-left .5s;
            padding: 16px;
            margin-left: 200px;
        }

        @@media screen and (max-height: 450px) {
            .sidenav {
                padding-top: 15px;
            }

                .sidenav a {
                    font-size: 18px;
                }
        }
    </style>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JMC.Portal.Web.UI</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
       
    @* Add the Kendo Bootstrap theme: *@
    <link href="https://kendo.cdn.telerik.com/2022.3.1109/styles/kendo.bootstrap-main.min.css" rel="stylesheet" type="text/css" />

    <script src="https://kendo.cdn.telerik.com/2022.3.1109/js/jquery.min.js"></script>

    <script src="https://kendo.cdn.telerik.com/2022.3.1109/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2022.3.1109/js/kendo.aspnetmvc.min.js"></script>

    @*    <script src="https://kendo.cdn.telerik.com/***/kendo.core.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/***/kendo.userevents.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/***/kendo.draganddrop.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/***/kendo.popup.min.js   "></script>
    <script src="https://kendo.cdn.telerik.com/***/kendo.fx.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/***/kendo.window.min.js"></script>*@
    <script src="~/js/kendo-ui-license.js"></script>

    <script>
        $(document).ready(function () {

            $("#sidenavBar li a").click(function () {

                var element = $(this);
                var isClosebtn = element[0].className == "closebtn";
                if (!isClosebtn) {
                    $("#sidenavBar li a.active").removeClass("active");
                    $(this).addClass("active");
                }
            });

            $("#dropdown-container li a").click(function () {
                $('.nav-item').removeClass('selected');
                $(this).parent().addClass('selected');
            });
                       

            $("#horizantalNavbar li a").click(function () {
                //debugger;

                //$(this).addClass("active");
                //$(this).addClass('active');
                //$('.nav-item').removeClass('selected');
                //$('.nav-link').removeClass('active');
                //$('.nav-link').addClass('active');
                //$(this).parent().addClass('selected');
            });
            
            var dropdown = document.getElementsByClassName("dropdown-btn");

           
            for (i = 0; i < dropdown.length; i++) {
                dropdown[i].addEventListener("click", function () {
                    this.classList.toggle("active");
                    var dropdownContent = this.nextElementSibling;
                    if (dropdownContent.style.display === "block") {
                        dropdownContent.style.display = "none";

                    } else {
                        dropdownContent.style.display = "block";

                    }
                });
            }


        })


        function openNav() {
            document.getElementById("sidenavBar").style.width = "200px";
            document.getElementById("main").style.marginLeft = "200px";
            document.getElementById("main").style.marginLeft = "200px";
            document.getElementById("productInquiry").style.display = "block";
        }

        function closeNav() {
            document.getElementById("sidenavBar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.getElementById("productInquiry").style.display = "none";
        }
    </script>
</head>
<body>
    <div style="margin:5px;">
        <span>Header</span>
    </div>

    <div class="wrapper">
        <div class="sidenav" id="sidenavBar">
            <input type="button" class="dropdown-btn btn btn-secondary" onclick="closeNav()" value="Close" />
            @await Component.InvokeAsync("SideMenu", new { mainMenu = ViewData["SelectedMenu"] })
        </div>         

        <div id="main">

            <span style="font-size:30px;cursor:pointer" onclick="openNav()"> &#9776;</span>
            <header>

                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
                    <div class="container">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            @await Component.InvokeAsync("Menu", new { testId = 1 })
                        </div>
                    </div>
                </nav>
            </header>
            <div id="ajaxContentRight">
                @RenderBody()
            </div>

        </div>
    </div>

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
 
    <link href="/css/jmc.portal.common.css<%:t %>" rel="stylesheet" type="text/css" />
        @RenderSection("Scripts", required: false)
        <script src="~/js/mvc-grid.js"></script>
         <script>
           document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
        </script>
</body>
</html>

JMC.Portal.Web.UI/Views/Shared/_Layout123.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
         <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.common-bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.bootstrap.min.css" />
    <script src="~/lib/kendo-ui-core/js/kendo.ui.core.min.js"></script>
     <link href="~/css/mvc-grid.css" rel="stylesheet">
</head>
<body style="background-color: #941800;">
    <div>
        @RenderBody()
        <script src="~/js/mvc-grid.js"></script>
         <script>
           document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
        </script>
    </div>
    <div>
        <footer style="color:white;">
            <div class="container">
                &copy; 2014 JMC Steel Group. All rights reserved.
            </div>
        </footer>
    </div>
</body>
</html>

JMC.Portal.Web.UI/Views/Shared/_LogOnLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
         <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.common-bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.bootstrap.min.css" />
    <script src="~/lib/kendo-ui-core/js/kendo.ui.core.min.js"></script>
</head>
<body style="background-color: #941800;">
    <div>
        @RenderBody()
    </div>
    <div>
        <footer style="color:white;">
            <div class="container">
                &copy; 2014 JMC Steel Group. All rights reserved.
            </div>
        </footer>
    </div>
</body>
</html>